const CardData = [
    {
		id : 1 ,
		cardName :"Bulbasaur",
		cardSet :"Shining Legends",
		setYear :"2017",
		img : "./img/bulbasaur.jpg",
	},
	{
		id : 2 ,
		cardName :"Ivysaur",
		cardSet :"151",
		setYear :"2023",
		img : "./img/ivysaur.jpg",
	},
	{
		id : 3 ,
		cardName :"Venusaur",
		cardSet :"Celebrations",
		setYear :"2021",
		img : "./img/venusaur.jpg",
	},
	{
		id : 4 ,
		cardName :"Charmander",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/charmander.jpg",
	},
	{
		id : 5 ,
		cardName :"Charmeleon",
		cardSet :"151",
		setYear :"2023",
		img : "./img/charmeleon.jpg",
	},
	{
		id : 6 ,
		cardName :"Charizard",
		cardSet :"Vivid Voltage",
		setYear :"2020",
		img : "./img/charizard.jpg",
	},
	{
		id : 7 ,
		cardName :"Squirtle",
		cardSet :"Base Set 2",
		setYear :"2000",
		img : "./img/squirtle.jpg",
	},
	{
		id : 8 ,
		cardName :"Wartortle",
		cardSet :"Pokémon Go",
		setYear :"2022",
		img : "./img/wartortle.jpg",
	},
	{
		id : 9 ,
		cardName :"Blastoise",
		cardSet :"Celebrations",
		setYear :"2021",
		img : "./img/blastoise.jpg",
	},
	{
		id : 10 ,
		cardName :"Caterpie",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/caterpie.jpg",
	},
	{
		id : 11 ,
		cardName :"Metapod",
		cardSet :"Base Set 2",
		setYear :"2000",
		img : "./img/metapod.jpg",
	},
	{
		id : 12 ,
		cardName :"Butterfree",
		cardSet :"151",
		setYear :"2023",
		img : "./img/buterfree.jpg",
	},
	{
		id : 13 ,
		cardName :"Weedle",
		cardSet :"151",
		setYear :"2023",
		img : "./img/weedle.jpg",
	},
	{
		id : 14 ,
		cardName :"Kakuna",
		cardSet :"151",
		setYear :"2023",
		img : "./img/kakuna.jpg",
	},
	{
		id : 15 ,
		cardName :"Beedrill",
		cardSet :"Evolutions",
		setYear :"2016",
		img : "./img/beedrill.jpg",
	},
	{
		id : 16 ,
		cardName :"Pidgey",
		cardSet :"151",
		setYear :"2023",
		img : "./img/pidgey.jpg",
	},
	{
		id : 17 ,
		cardName :"Pidgeotto",
		cardSet :"151",
		setYear :"2023",
		img : "./img/pidgeotto.jpg",
	},
	{
		id : 18 ,
		cardName :"Pidgeot",
		cardSet :"151",
		setYear :"2023",
		img : "./img/pidgeot.jpg",
	},
	{
		id : 19 ,
		cardName :"Rattata",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/rattata.jpg",
	},
	{
		id : 20 ,
		cardName :"Raticate",
		cardSet :"Evolutions",
		setYear :"2016",
		img : "./img/raticate.jpg",
	},
	{
		id : 21 ,
		cardName :"Spearow",
		cardSet :"151",
		setYear :"2023",
		img : "./img/spearow.jpg",
	},
	{
		id : 22 ,
		cardName :"Fearow",
		cardSet :"151",
		setYear :"2023",
		img : "./img/fearow.jpg",
	},
	{
		id : 23 ,
		cardName :"Ekans",
		cardSet :"151",
		setYear :"2023",
		img : "./img/ekans.jpg",
	},
	{
		id : 24 ,
		cardName :"Arbok",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/arbok.jpg",
	},
	{
		id : 25 ,
		cardName :"Pikachu",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/pikachu.jpg",
	},
	{
		id : 26 ,
		cardName :"Raichu",
		cardSet :"151",
		setYear :"2023",
		img : "./img/raichu.jpg",
	},
	{
		id : 27 ,
		cardName :"Sandshrew",
		cardSet :"151",
		setYear :"2023",
		img : "./img/sandshrew.jpg",
	},
	{
		id : 28 ,
		cardName :"Sandslash",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/sandslash.jpg",
	},
	{
		id : 29 ,
		cardName :"Nidoran",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/nidoranF.jpg",
	},
	{
		id : 30 ,
		cardName :"Nidorina",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/nidorina.jpg",
	},
	{
		id : 31 ,
		cardName :"Nidoqueen",
		cardSet :"151",
		setYear :"2023",
		img : "./img/nidoqueen.jpg",
	},
    {
		id : 32 ,
		cardName :"Nidoran",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/nidoranM.jpg",
	},
	{
		id : 33 ,
		cardName :"Nidorino",
		cardSet :"Triumphant",
		setYear :"2010",
		img : "./img/nidorino.jpg",
	},
	{
		id : 34 ,
		cardName :"Nidoking",
		cardSet :"151",
		setYear :"2023",
		img : "./img/nidoking.jpg",
	},
	{
		id : 35 ,
		cardName :"Clefairy",
		cardSet :"151",
		setYear :"2023",
		img : "./img/clefairy.jpg",
	},
	{
		id : 36 ,
		cardName :"Clefable",
		cardSet :"Generations",
		setYear :"2016",
		img : "./img/clefable.jpg",
	},
	{
		id : 37 ,
		cardName :"Vulpix",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/vulpix.jpg",
	},
	{
		id : 38 ,
		cardName :"Ninetales",
		cardSet :"Sword & Shield",
		setYear :"2020",
		img : "./img/ninetales.jpg",
	},
	{
		id : 39 ,
		cardName :"Jigglypuff",
		cardSet :"151",
		setYear :"2023",
		img : "./img/jigglypuff.jpg",
	},
	{
		id : 40 ,
		cardName :"Wigglytuff",
		cardSet :"Crimson Invasion",
		setYear :"2017",
		img : "./img/wigglytuff.jpg",
	},
	{
		id : 41 ,
		cardName :"Zubat",
		cardSet :"151",
		setYear :"2023",
		img : "./img/zubat.jpg",
	},
	{
		id : 42 ,
		cardName :"Golbat",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/golbat.jpg",
	},
	{
		id : 43 ,
		cardName :"Oddish",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/oddish.jpg",
	},
	{
		id : 44 ,
		cardName :"Gloom",
		cardSet :"151",
		setYear :"2023",
		img : "./img/gloom.jpg",
	},
	{
		id : 45 ,
		cardName :"Vileplume",
		cardSet :"Ancient Origins",
		setYear :"2015",
		img : "./img/vileplume.jpg",
	},
	{
		id : 46 ,
		cardName :"Paras",
		cardSet :"151",
		setYear :"2023",
		img : "./img/paras.jpg",
	},
	{
		id : 47 ,
		cardName :"Parasect",
		cardSet :"151",
		setYear :"2023",
		img : "./img/parasect.jpg",
	},
	{
		id : 48 ,
		cardName :"Venonat",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/venonat.jpg",
	},
	{
		id : 49 ,
		cardName :"Venomoth",
		cardSet :"151",
		setYear :"2023",
		img : "./img/venomoth.jpg",
	},
	{
		id : 50 ,
		cardName :"Diglett",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/diglett.jpg",
	},
	{
		id : 51 ,
		cardName :"Dugtrio",
		cardSet :"151",
		setYear :"2023",
		img : "./img/dugtrio.jpg",
	},
	{
		id : 52 ,
		cardName :"Meowth",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/meowth.jpg",
	},
	{
		id : 53 ,
		cardName :"Persian",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/persian.jpg",
	},
	{
		id : 54 ,
		cardName :"Psyduck",
		cardSet :"Astral Radiance",
		setYear :"2022",
		img : "./img/psyduck.jpg",
	},
	{
		id : 55 ,
		cardName :"Golduck",
		cardSet :"151",
		setYear :"2023",
		img : "./img/golduck.jpg",
	},
	{
		id : 56 ,
		cardName :"Mankey",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/mankey.jpg",
	},
	{
		id : 57 ,
		cardName :"Primeape",
		cardSet :"Scarlet & Violet",
		setYear :"2023",
		img : "./img/primeape.jpg",
	},
	{
		id : 58 ,
		cardName :"Growlithe",
		cardSet :"Fusion Strike",
		setYear :"2021",
		img : "./img/growlithe.jpg",
	},
	{
		id : 59 ,
		cardName :"Arcanine",
		cardSet :"Evolutions",
		setYear :"2016",
		img : "./img/arcanine.jpg",
	},
	{
		id : 60 ,
		cardName :"Poliwag",
		cardSet :"151",
		setYear :"2023",
		img : "./img/poliwag.jpg",
	},
	{
		id : 61 ,
		cardName :"Poliwhirl",
		cardSet :"151",
		setYear :"2023",
		img : "./img/poliwhirl.jpg",
	},
	{
		id : 62 ,
		cardName :"Poliwrath",
		cardSet :"151",
		setYear :"2023",
		img : "./img/poliwrath.jpg",
	},
	{
		id : 63 ,
		cardName :"Abra",
		cardSet :"151",
		setYear :"2023",
		img : "./img/abra.jpg",
	},
	{
		id : 64 ,
		cardName :"Kadabra",
		cardSet :"151",
		setYear :"2023",
		img : "./img/kadabra.jpg",
	},
	{
		id : 65 ,
		cardName :"Alakazam",
		cardSet :"Scarlet & Violet",
		setYear :"2023",
		img : "./img/alakazam.jpg",
	},
	{
		id : 66 ,
		cardName :"Machop",
		cardSet :"151",
		setYear :"2023",
		img : "./img/machop.jpg",
	},
	{
		id : 67 ,
		cardName :"Machoke",
		cardSet :"151",
		setYear :"2023",
		img : "./img/machoke.jpg",
	},
	{
		id : 68 ,
		cardName :"Machamp",
		cardSet :"Base Set (1st)",
		setYear :"1999",
		img : "./img/machamp.jpg",
	},
	{
		id : 69 ,
		cardName :"Bellsprout",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/bellsprout.jpg",
	},
	{
		id : 70 ,
		cardName :"Weepinbell",
		cardSet :"151",
		setYear :"2023",
		img : "./img/weepinbell.jpg",
	},
	{
		id : 71 ,
		cardName :"Victreebel",
		cardSet :"151",
		setYear :"2023",
		img : "./img/victreebel.jpg",
	},
	{
		id : 72 ,
		cardName :"Tentacool",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/tentacool.jpg",
	},
	{
		id : 73 ,
		cardName :"Tentacruel",
		cardSet :"Triumphant",
		setYear :"2010",
		img : "./img/tentacruel.jpg",
	},
	{
		id : 74 ,
		cardName :"Geodude",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/geodude.jpg",
	},
	{
		id : 75 ,
		cardName :"Graveler",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/graveler.jpg",
	},
	{
		id : 76 ,
		cardName :"Golem",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/golem.jpg",
	},
	{
		id : 77 ,
		cardName :"Ponyta",
		cardSet :"Team Rocket",
		setYear :"2007",
		img : "./img/ponyta.jpg",
	},
	{
		id : 78 ,
		cardName :"Rapidash",
		cardSet :"Temporal Forces",
		setYear :"2024",
		img : "./img/rapidash.jpg",
	},
	{
		id : 79 ,
		cardName :"Slowpoke",
		cardSet :"151",
		setYear :"2023",
		img : "./img/slowpoke.jpg",
	},
	{
		id : 80 ,
		cardName :"Slowbro",
		cardSet :"Pokémon Go",
		setYear :"2022",
		img : "./img/slowbro.jpg",
	},
	{
		id : 81 ,
		cardName :"Magnemite",
		cardSet :"Team Rocket",
		setYear :"2007",
		img : "./img/magnemite.jpg",
	},
	{
		id : 82 ,
		cardName :"Magneton",
		cardSet :"151",
		setYear :"2023",
		img : "./img/magneton.jpg",
	},
	{
		id : 83 ,
		cardName :"Farfetch'd",
		cardSet :"151",
		setYear :"2023",
		img : "./img/farfetchd.jpg",
	},
	{
		id : 84 ,
		cardName :"Doduo",
		cardSet :"Base Set 2",
		setYear :"2000",
		img : "./img/doduo.jpg",
	},
	{
		id : 85 ,
		cardName :"Dodrio",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/dodrio.jpg",
	},
	{
		id : 86 ,
		cardName :"Seel",
		cardSet :"Neo Destiny",
		setYear :"2002",
		img : "./img/seel.jpg",
	},
	{
		id : 87 ,
		cardName :"Dewgong",
		cardSet :"Evolutions",
		setYear :"2019",
		img : "./img/dewgong.jpg",
	},
	{
		id : 88 ,
		cardName :"Grimer",
		cardSet :"Team Rocket",
		setYear :"2007",
		img : "./img/grimer.jpg",
	},
	{
		id : 89 ,
		cardName :"Muk",
		cardSet :"Brilliant Stars",
		setYear :"2002",
		img : "./img/muk.jpg",
	},
	{
		id : 90 ,
		cardName :"Shellder",
		cardSet :"151",
		setYear :"2023",
		img : "./img/shellder.jpg",
	},
	{
		id : 91 ,
		cardName :"Cloyster",
		cardSet :"151",
		setYear :"2023",
		img : "./img/cloyster.jpg",
	},
	{
		id : 92 ,
		cardName :"Gastly",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/gastly.jpg",
	},
	{
		id : 93 ,
		cardName :"Haunter",
		cardSet :"Evolutions",
		setYear :"2016",
		img : "./img/haunter.jpg",
	},
	{
		id : 94 ,
		cardName :"Gengar",
		cardSet :"151",
		setYear :"2023",
		img : "./img/gengar.jpg",
	},
	{
		id : 95 ,
		cardName :"Onix",
		cardSet :"Fusion Strike",
		setYear :"2023",
		img : "./img/onix.jpg",
	},
	{
		id : 96 ,
		cardName :"Drowzee",
		cardSet :"Team Rocket",
		setYear :"2007",
		img : "./img/drowzee.jpg",
	},
	{
		id : 97 ,
		cardName :"Hypno",
		cardSet :"Furious Fists",
		setYear :"2014",
		img : "./img/hypno.jpg",
	},
	{
		id : 98 ,
		cardName :"Krabby",
		cardSet :"151",
		setYear :"2023",
		img : "./img/krabby.jpg",
	},
	{
		id : 99 ,
		cardName :"Kingler",
		cardSet :"151",
		setYear :"2023",
		img : "./img/kingler.jpg",
	},
	{
		id : 100 ,
		cardName :"Voltorb",
		cardSet :"151",
		setYear :"2023",
		img : "./img/voltorb.jpg",
	},
	{
		id : 101 ,
		cardName :"Electrode",
		cardSet :"151",
		setYear :"2023",
		img : "./img/electrode.jpg",
	},
	{
		id : 102 ,
		cardName :"Exeggcute",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/exeggcute.jpg",
	},
	{
		id : 103 ,
		cardName :"Exeggutor",
		cardSet :"151",
		setYear :"2023",
		img : "./img/exeggutor.jpg",
	},
	{
		id : 104 ,
		cardName :"Cubone",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/cubone.jpg",
	},
	{
		id : 105 ,
		cardName :"Marowak",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/marowak.jpg",
	},
	{
		id : 106 ,
		cardName :"Hitmonlee",
		cardSet :"Neo Destiny ",
		setYear :"2002",
		img : "./img/hitmonlee.jpg",
	},
	{
		id : 107 ,
		cardName :"Hitmonchan",
		cardSet :"Evolving Skies",
		setYear :"2021",
		img : "./img/hitmonchan.jpg",
	},
	{
		id : 108 ,
		cardName :"Lickitung",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/lickitung.jpg",
	},
	{
		id : 109 ,
		cardName :"Koffing",
		cardSet :"Team Rocket",
		setYear :"2007",
		img : "./img/koffing.jpg",
	},
	{
		id : 110 ,
		cardName :"Weezing",
		cardSet :"151",
		setYear :"2023",
		img : "./img/weezing.jpg",
	},
	{
		id : 111 ,
		cardName :"Rhyhorn",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/rhyhorn.jpg",
	},
	{
		id : 112 ,
		cardName :"Rhydon",
		cardSet :"151",
		setYear :"2023",
		img : "./img/rhydon.jpg",
	},
	{
		id : 113 ,
		cardName :"Chansey",
		cardSet :"151",
		setYear :"2023",
		img : "./img/chansey.jpg",
	},
	{
		id : 114 ,
		cardName :"Tangela",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/tangela.jpg",
	},
	{
		id : 115 ,
		cardName :"Kangaskhan",
		cardSet :"Triumphant",
		setYear :"2010",
		img : "./img/kangaskhan.jpg",
	},
    {
		id : 116 ,
		cardName :"Horsea",
		cardSet :"151",
		setYear :"2023",
		img : "./img/horsea.jpg",
	},
	{
		id : 117 ,
		cardName :"Seadra",
		cardSet :"151",
		setYear :"2023",
		img : "./img/seadra.jpg",
	},
	{
		id : 118 ,
		cardName :"Goldeen",
		cardSet :"151",
		setYear :"2023",
		img : "./img/goldeen.jpg",
	},
	{
		id : 119 ,
		cardName :"Seaking",
		cardSet :"151",
		setYear :"2023",
		img : "./img/seaking.jpg",
	},
	{
		id : 120 ,
		cardName :"Staryu",
		cardSet :"151",
		setYear :"2023",
		img : "./img/staryu.jpg",
	},
	{
		id : 121 ,
		cardName :"Starmie",
		cardSet :"Brilliant Stars",
		setYear :"2022",
		img : "./img/starmie.jpg",
	},
	{
		id : 122 ,
		cardName :"Mr. Mime",
		cardSet :"Temporal Forces",
		setYear :"2024",
		img : "./img/mrmime.jpg",
	},
	{
		id : 123 ,
		cardName :"Scyther",
		cardSet :"151",
		setYear :"2023",
		img : "./img/scyther.jpg",
	},
	{
		id : 124 ,
		cardName :"Jynx",
		cardSet :"Base Set",
		setYear :"1999",
		img : "./img/jynx.jpg",
	},
	{
		id : 125 ,
		cardName :"Electabuzz",
		cardSet :"151",
		setYear :"2023",
		img : "./img/electabuzz.jpg",
	},
	{
		id : 126 ,
		cardName :"Magmar",
		cardSet :"151",
		setYear :"2023",
		img : "./img/magmar.jpg",
	},
	{
		id : 127 ,
		cardName :"Pinsir",
		cardSet :"Lost Thunder",
		setYear :"2018",
		img : "./img/pinsir.jpg",
	},
	{
		id : 128 ,
		cardName :"Tauros",
		cardSet :"Jungle",
		setYear :"1999",
		img : "./img/tauros.jpg",
	},
	{
		id : 129 ,
		cardName :"Magikarp",
		cardSet :"151",
		setYear :"2023",
		img : "./img/magikarp.jpg",
	},
	{
		id : 130 ,
		cardName :"Gyarados",
		cardSet :"151",
		setYear :"2023",
		img : "./img/gyarados.jpg",
	},
	{
		id : 131 ,
		cardName :"Lapras",
		cardSet :"151",
		setYear :"2023",
		img : "./img/lapras.jpg",
	},
	{
		id : 132 ,
		cardName :"Ditto",
		cardSet :"151",
		setYear :"2023",
		img : "./img/ditto.jpg",
	},
	{
		id : 133 ,
		cardName :"Eevee",
		cardSet :"Team Rocket",
		setYear :"2007",
		img : "./img/eevee.jpg",
	},
	{
		id : 134 ,
		cardName :"Vaporeon",
		cardSet :"151",
		setYear :"2023",
		img : "./img/vaporeon.jpg",
	},
	{
		id : 135 ,
		cardName :"Jolteon",
		cardSet :"151",
		setYear :"2023",
		img : "./img/jolteon.jpg",
	},
	{
		id : 136 ,
		cardName :"Flareon",
		cardSet :"Vivid Voltage",
		setYear :"2020",
		img : "./img/flareon.jpg",
	},
	{
		id : 137 ,
		cardName :"Porygon",
		cardSet :"Evolutions",
		setYear :"2016",
		img : "./img/porygon.jpg",
	},
	{
		id : 138 ,
		cardName :"Omanyte",
		cardSet :"151",
		setYear :"2023",
		img : "./img/omanyte.jpg",
	},
	{
		id : 139 ,
		cardName :"Omastar",
		cardSet :"Neo Discovery",
		setYear :"2001",
		img : "./img/omastar.jpg",
	},
	{
		id : 140 ,
		cardName :"Kabuto",
		cardSet :"Fossil",
		setYear :"1999",
		img : "./img/kabuto.jpg",
	},
	{
		id : 141 ,
		cardName :"Kabutops",
		cardSet :"151",
		setYear :"2023",
		img : "./img/kabutops.jpg",
	},
	{
		id : 142 ,
		cardName :"Aerodactyl",
		cardSet :"151",
		setYear :"2023",
		img : "./img/aerodactyl.jpg",
	},
	{
		id : 143 ,
		cardName :"Snorlax",
		cardSet :"Fusion Strike",
		setYear :"2021",
		img : "./img/snorlax.jpg",
	},
	{
		id : 144 ,
		cardName :"Articuno",
		cardSet :"Silver Tempest",
		setYear :"2002",
		img : "./img/articuno.jpg",
	},
	{
		id : 145 ,
		cardName :"Zapdos",
		cardSet :"Hidden Fates",
		setYear :"2019",
		img : "./img/zapdos.jpg",
	},
	{
		id : 146 ,
		cardName :"Moltres",
		cardSet :"Brilliant Stars",
		setYear :"2022",
		img : "./img/moltres.jpg",
	},
	{
		id : 147 ,
		cardName :"Dratini",
		cardSet :"Sun & Moon",
		setYear :"2017",
		img : "./img/dratini.jpg",
	},
	{
		id : 148 ,
		cardName :"Dragonair",
		cardSet :"151",
		setYear :"2023",
		img : "./img/dragonair.jpg",
	},
	{
		id : 149 ,
		cardName :"Dragonite",
		cardSet :"Silver Tempest",
		setYear :"2022",
		img : "./img/dragonite.jpg",
	},
	{
		id : 150 ,
		cardName :"Mewtwo",
		cardSet :"Crown Zenith",
		setYear :"2023",
		img : "./img/mewtwo.jpg",
	},
	{
		id : 151 ,
		cardName :"Mew",
		cardSet :"Hidden Fates",
		setYear :"2019",
		img : "./img/mew.jpg",
	},

]

export default CardData;
